### ISSUE TITLE
dqrunif same min and max values fatal error

### ISSUE THREAD

**Issue by isezen** [daqana/dqrng#33] opened 2019-06-28 15:30 UTC
If `min` and `max` values are same in `dqrunif`, R session is aborted.

```R
dqrng::dqrunif(5, min = 10, max = 10)
```

**Comment by LTLA** [comment] 2019-06-29 06:33
Can't reproduce this with 0.2.1 (Ubuntu, R 3.6.0).

Having said that, I have observed issues elsewhere with `boost::random::uniform_real_distribution` when `min` and `max` are equal. In my case, it resulted in the program stalling (MarioniLab/DropletUtils#14). I didn't dig into it further because I changed my sampling scheme anyway, but this might be related.

**Comment by isezen** [comment] 2019-06-29 14:21
Excuse me, My session info is below. Perhaps, it helps.

```R
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] microbenchmark_1.4-6 colorout_1.2-0       lintr_1.0.3         

loaded via a namespace (and not attached):
[1] compiler_3.5.2 lazyeval_0.2.2 magrittr_1.5   tools_3.5.2    rex_1.1.2      yaml_2.2.0 
```

**Comment by rstub** [comment] 2019-06-30 08:50
I cannot reproduce this either, but there is room for optimization in `dqrunif`:

* There is no need to use the RNG if `min == max`.
* It would make sense to return an error if `min > max`. Currently they are simply swapped by `boost::random::uniform_distribution`.

**Comment by isezen** [comment] 2019-06-30 09:33
as @LTLA said, I encountered this error while using `boost::random::uniform_real_distribution` but same issue also exists for `dqrunif `. I solved it by `if (min == max) return(min);` for myself. Just wanted to let you know.

**Comment by rstub** [comment] 2019-06-30 13:30
@isezen Can you give #34 a try?

**Comment by isezen** [comment] 2019-06-30 14:20
I've installed the pull by `remotes::install_github("daqana/dqrng#34")` and it works right now. But I think the pull was not merged into master.

**Comment by rstub** [comment] 2019-06-30 14:44
It has been merged now ...

**Closed** 2019-06-30 14:44 UTC
